---
- name: Ubuntu-16 | Create directories
  file:
   path={{ item }}
   state=directory
   mode=0755
  with_items:
   - /etc/supervisor
   - /etc/supervisor/conf.d
   - /var/log/supervisor

- name: Ubuntu-16 | Install python-setuptools
  apt:
   name=python-setuptools
   state=latest
   update_cache=yes

- name: Ubuntu-16 | Install supervisor
  easy_install:
   name=supervisor
   state=present

- block:
  - name: Ubuntu-16 | Display supervisord.conf src location if defined
    debug: msg="path {{ supervisor_conf }}"

  - name: Ubuntu-16 | Copy supervisor main config to /etc/supervisor/supervisord.conf
    template:
     src={{ supervisor_conf }}
     dest=/etc/supervisor/supervisord.conf
    register: supervisor_cfg_file
  when: supervisor_conf is defined


- name: Ubuntu-16 | Copy init script to /etc/init.d/supervisor
  template:
   src=Ubuntu-16/init.supervisor.j2
   dest=/etc/init.d/supervisor
   mode=0755

- block:
  - name: Ubuntu-16 | Debug print supervisor_conf_d path
    debug: var=supervisor_conf_d

  - name: Ubuntu-16 | Copy config files to conf.d on remote
    template:
      src={{ item }}
      dest=/etc/supervisor/conf.d/{{ item | basename }}
      owner=root
      group=root
      mode=0440
    with_fileglob:
      - "{{ supervisor_conf_d }}/*.conf"
    notify: supervisor restart
  when: supervisor_conf_d is defined

- name: Ubuntu-16 | restart and enable supervisor service and
  service:
    name=supervisor
    state=restarted
    enabled=yes
  when: supervisor_cfg_file|changed
